### ISSUE TITLE
s3-workspace files error

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/example-async-compute-service#2]
```
service_1               |  java.lang.StringIndexOutOfBoundsException: begin 33, end 6, length 6
service_1               |       at java.lang.String.checkBoundsBeginEnd(String.java:4548) ~[?:?]
service_1               |       at java.lang.String.substring(String.java:2704) ~[?:?]
service_1               |       at java.lang.String.substring(String.java:2677) ~[?:?]
service_1               |       at org.veupathdb.lib.s3.workspaces.impl.S3WorkspaceImpl.files(S3WorkspaceImpl.kt:58) ~[service.jar:1.0.0]
service_1               |       at org.veupathdb.lib.compute.platform.intern.s3.S3.getResultFiles(S3.kt:101) ~[service.jar:1.0.0]
service_1               |       at org.veupathdb.lib.compute.platform.AsyncPlatform.getJobResults(AsyncPlatform.kt:164) ~[service.jar:1.0.0]
service_1               |       at org.veupathdb.service.demo.service.JobController.getJobsFilesByJobId(JobController.java:26) ~[service.jar:1.0.0]
service_1               |       at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
service_1               |       at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
service_1               |       at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
service_1               |       at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
service_1               |       at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) ~[service.jar:1.0.0]
service_1               |       at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) ~[service.jar:1.0.0]
service_1               |       at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by Foxcapades** [comment]
probably related to the s34k-minio prefix bug.

**Comment by Foxcapades** [comment]
resolved by fix to s34k-minio
